### ISSUE TITLE
MGet action crash when some keys are not found

### ISSUE THREAD

**Issue by xaerocom** [No3371/go-skytable#3]
When I'm trying to retrieve mutliple values via mget action and some keys in skytable are not present, result will fail on this error:

failed execution: failed to read from conn: an error occured when reading entry#1/1: failed to read typed array entry #9/11: strconv.ParseInt: parsing "\x00": invalid syntax

Is that an expected behaviour?

**Comment by No3371** [comment]
Just in case, are you running Skytable 0.8 or 0.7?

**Comment by No3371** [comment]
Please see if the fix works for you, thanks.

**Comment by xaerocom** [comment]
I'm using Skytable 0.7.6. Right now I'm getting a different error:
panic: interface conversion: interface {} is nil, not []uint8

**Comment by xaerocom** [comment]
Yes it's working now. Elements needs to be checked on nil type and all is fine. Thanks!
